### ISSUE TITLE
This is genius

### ISSUE THREAD

**Issue by mikeborozdin** [gabotechs/signway#8]
Hi @gabotechs ,

The approach of using short lived pre-signed URL is genius!

I was looking to solve the same problem - how to use serverless functions and stream results.

I was thinking of building a cloud service that would do that. Although the developer experience and security would be no as great as yours, as you would have to expose the API key of the cloud service to the frontend. I built a [landing page](https://aistream.dev/) for it, but didn't get enough traction and abandoned the idea.

That said, I recently released [a library ](https://www.npmjs.com/package/http-streaming-request)for processing streamed JSON on the frontend.

Anyway, very well done!

And, by the way, the waiting list on your website seems broken. It shows me a 404. after I fill it in.

**Comment by gabotechs** [comment]
Hi @mikeborozdin, glad that you liked it!

> And, by the way, the waiting list on your website seems broken. It shows me a 404. after I fill it in.

thanks for pointing that out! I have just fixed it.

> I was thinking of building a cloud service that would do that. Although the developer experience and security would be no as great as yours, as you would have to expose the API key of the cloud service to the frontend. I built a [landing page](https://aistream.dev/) for it, but didn't get enough traction and abandoned the idea.

I feel you, I also created that landing page to see how much traction that could get, and even though there were a couple of people showing some interest here and there, it did not got the traction I expected and I am not dedicating much time to the idea now.

> That said, I recently released [a library ](https://www.npmjs.com/package/http-streaming-request)for processing streamed JSON on the frontend.

I just took a look, and it looks like it could play along really really well with a service like Signway, as it doesn't provide any frontend utility for handling the streaming data.

**Comment by mikeborozdin** [comment]
> I feel you, I also created that landing page to see how much traction that could get, and even though there were a couple of people showing some interest here and there, it did not got the traction I expected and I am not dedicating much time to the idea now.

Ouch, that's sad. Did you manage to promote it anyhow?

In my experience, I was working on [one project](https://powermodeai.com/) which had serverless backend - Firebase Functions - and I introduced streaming. I just went for Cloud Run - wasn't too bad in the end.

Also now Vercel has support for streaming from their [Edge Functions](https://vercel.com/docs/functions/edge-functions/streaming). And if you use Next.js - it's even easier to integrate. And that's what I use for [my other project](https://www.noecho.news/).

> I just took a look, and it looks like it could play along really really well with a service like Signway, as it doesn't provide any frontend utility for handling the streaming data.

Feel free to integrate it then :). I'm more than happy to help with that. Also even [Vercel AI SDK](https://sdk.vercel.ai/docs)does not do anything to help with steaming JSON data.

**Comment by gabotechs** [comment]
> Ouch, that's sad. Did you manage to promote it anyhow?

Only in social media, nothing fancy. There are a lot of alternatives now that are also valid.

> Feel free to integrate it then :). I'm more than happy to help with that.

Thanks!, I'm not sure how that would play out, as this is just a rust compiled binary + a docker image. But I'm sure client-side consumers would find your package very useful!
